background            #262624
foreground            #e6e6e6

cursor                #e6e6e6
selection_background  #e6e6e6
selection_foreground  #262624

color0                #1f1f1d
color1                #2e5b51
color2                #244e45
color3                #60bba8
color4                #3e6e62
color5                #174136
color6                #53867c
color7                #a8c2bc

color8                #272724
color9                #3a7265
color10               #2d6256
color11               #91d0c3
color12               #4e897b
color13               #1d5144
color14               #6ba499
color15               #dde7e5
